# fly.toml app configuration file generated for reactivities-project-ver2 on 2023-05-02T13:00:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-project-ver2"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "mikaelaurell/reactivities:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "544222488222221"
  Cloudinary__CloudName = "dtqbmlysa"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
