export const Birds = [
    { id: 0, text: 'SWE', value: 'Koltrast', checked: false, category: 'TRASTAR' },
    { id: 1, text: 'SWE', value: 'Taltrast', checked: false, category: 'TRASTAR' },
    { id: 2, text: 'ENG', value: 'Common Blackbird', checked: false, category: null },
    { id: 3, text: 'SWE', value: 'Blåmes', checked: false, category: null },
    { id: 4, text: 'ENG', value: 'Eurasian Blue Tit', checked: false, category: null },
    { id: 5, text: 'SWE', value: 'Fiskmås', checked: false, category: null },
    { id: 6, text: 'ENG', value: 'European Herring Gull', checked: false, category: null },
    { id: 7, text: 'ENG', value: 'Eurasian Blue Tit', checked: false, category: null },
    { id: 8, text: 'SWE', value: 'Bofink', checked: false, category: null },
    { id: 9, text: 'ENG', value: 'Common Chaffinch', checked: false, category: null },
    { id: 10, text: 'SWE', value: 'Fiskmås', checked: false, category: null },
    { id: 11, text: 'ENG', value: 'European Herring Gull', checked: false, category: null },
    { id: 12, text: 'SWE', value: 'Grönfink', checked: false, category: null },
    { id: 13, text: 'ENG', value: 'European Greenfinch', checked: false, category: null },
    { id: 14, text: 'SWE', value: 'Gråsparv', checked: false, category: null },
    { id: 15, text: 'ENG', value: 'House Sparrow', checked: false, category: null },
    { id: 16, text: 'SWE', value: 'Gråhakedopping', checked: false, category: null },
    { id: 17, text: 'ENG', value: 'Red-necked Grebe', checked: false, category: null },
    { id: 18, text: 'SWE', value: 'Gulsparv', checked: false, category: null },
    { id: 19, text: 'ENG', value: 'Yellowhammer', checked: false, category: null },
    { id: 20, text: 'SWE', value: 'Järnsparv', checked: false, category: null },
    { id: 21, text: 'ENG', value: 'Snow Bunting', checked: false, category: null },
    { id: 22, text: 'SWE', value: 'Kaja', checked: false, category: null },
    { id: 23, text: 'ENG', value: 'Western Jackdaw', checked: false, category: null },
    { id: 24, text: 'SWE', value: 'Lappmes', checked: false, category: null },
    { id: 25, text: 'ENG', value: 'Siberian Jay', checked: false, category: null },
    { id: 26, text: 'SWE', value: 'Prärielärka', checked: false, category: null },
    { id: 27, text: 'ENG', value: 'Horned Lark', checked: false, category: null },
    { id: 28, text: 'SWE', value: 'Ringduva', checked: false, category: null },
    { id: 29, text: 'ENG', value: 'Common Wood Pigeon', checked: false, category: null },
    { id: 30, text: 'SWE', value: 'Rödhake', checked: false, category: null },
    { id: 31, text: 'ENG', value: 'European Robin', checked: false, category: null },
    { id: 32, text: 'SWE', value: 'Sävsparv', checked: false, category: null },
    { id: 33, text: 'ENG', value: 'Reed Bunting', checked: false, category: null },
    { id: 34, text: 'SWE', value: 'Skata', checked: false, category: null },
    { id: 35, text: 'ENG', value: 'Eurasian Magpie', checked: false, category: null },
    { id: 36, text: 'SWE', value: 'Sånglärka', checked: false, category: null },
    { id: 37, text: 'ENG', value: 'Eurasian Skylark', checked: false, category: null },
    { id: 38, text: 'SWE', value: 'Svartvit flugsnappare', checked: false, category: null },
    { id: 39, text: 'ENG', value: 'Pied Flycatcher', checked: false, category: null },
    { id: 40, text: 'SWE', value: 'Talgoxe', checked: false, category: null },
    { id: 41, text: 'ENG', value: 'Great Tit', checked: false, category: null },
    { id: 42, text: 'SWE', value: 'Tofsvipa', checked: false, category: null },
    { id: 43, text: 'ENG', value: 'Northern Lapwing', checked: false, category: null },
    { id: 44, text: 'SWE', value: 'Tornseglare', checked: false, category: null },
    { id: 45, text: 'ENG', value: 'Common Swift', checked: false, category: null },
    { id: 46, text: 'SWE', value: 'Trädpiplärka', checked: false, category: null },
    { id: 47, text: 'ENG', value: 'Tree Pipit', checked: false, category: null },
    { id: 48, text: 'SWE', value: 'Havsörn', checked: false, category: 'ROVFAGLAR' },
    { id: 49, text: 'SWE', value: 'Kungsörn', checked: false, category: 'ROVFAGLAR' },
    { id: 50, text: 'SWE', value: 'Trana', checked: false, category: null },
    { id: 51, text: 'SWE', value: 'Svan', checked: false, category: null },
    { id: 52, text: 'SWE', value: 'Sädesärla', checked: false, category: null }
]