export const Birds = [
    { id: 0, text: 'SWE', value: 'Koltrast', checked: false, category: 'TRASTAR' },
    { id: 1, text: 'SWE', value: 'Taltrast', checked: false, category: 'TRASTAR' },
    { id: 2, text: 'SWE', value: 'Fiskmås', checked: false, category: null },
    { id: 3, text: 'SWE', value: 'Grönfink', checked: false, category: null },
    { id: 4, text: 'SWE', value: 'Gråsparv', checked: false, category: null },
    { id: 5, text: 'SWE', value: 'Gråhakedopping', checked: false, category: null },
    { id: 6, text: 'SWE', value: 'Gulsparvk', checked: false, category: null },
    { id: 7, text: 'SWE', value: 'Järnsparv', checked: false, category: null },
    { id: 8, text: 'SWE', value: 'Kaja', checked: false, category: null },
    { id: 9, text: 'SWE', value: 'Lappmes', checked: false, category: null },
    { id: 10, text: 'SWE', value: 'Prärielärka', checked: false, category: null },
    { id: 11, text: 'SWE', value: 'Blåmes', checked: false, category: null },
    { id: 12, text: 'SWE', value: 'Ringduva', checked: false, category: null },
    { id: 13, text: 'SWE', value: 'Rödhake', checked: false, category: null },
    { id: 14, text: 'SWE', value: 'Sävsparv', checked: false, category: null },
    { id: 15, text: 'SWE', value: 'Skata', checked: false, category: null },
    { id: 16, text: 'SWE', value: 'Sånglärka', checked: false, category: null },
    { id: 17, text: 'SWE', value: 'Svartvit flugsnappare', checked: false, category: null },
    { id: 18, text: 'SWE', value: 'Talgoxe', checked: false, category: null },
    { id: 19, text: 'SWE', value: 'Tofsvipa', checked: false, category: null },
    { id: 20, text: 'SWE', value: 'Tornseglare', checked: false, category: null },
    { id: 21, text: 'SWE', value: 'Trädpiplärka', checked: false, category: null },
    { id: 22, text: 'SWE', value: 'Fiskmås', checked: false, category: null },
    { id: 23, text: 'SWE', value: 'Havsörn', checked: false, category: null },
    { id: 24, text: 'SWE', value: 'Kungsörn', checked: false, category: 'ROVFAGLAR' },
    { id: 25, text: 'SWE', value: 'Trana', checked: false, category: 'ROVFAGLAR' },
    { id: 26, text: 'SWE', value: 'Svan', checked: false, category: null },
    { id: 27, text: 'SWE', value: 'Sädesärla', checked: false, category: null },
    { id: 28, text: 'SWE', value: 'Blåmes', checked: false, category: null },
    { id: 28, text: 'SWE', value: 'Bofink', checked: false, category: null }
]